name: Code Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - develop
      - 'releases/**'

permissions: {}

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:

    - name: Checkout repository
      uses: actions/checkout@v5
      # Checkout must run before the caching key is computed using the `hashFiles` method
    
    - name: Cache Gradle Modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches/modules-2/
          ~/.gradle/caches/build-cache-1/
          ~/.gradle/caches/signatures/
          ~/.gradle/caches/keyrings/
        key: ${{ runner.os }}-gradle-cache-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - name: Disable checksum offloading
      # See: https://github.com/actions/virtual-environments/issues/1187#issuecomment-686735760
      run: sudo ethtool -K eth0 tx off rx off

    - name: Set up JDK 25 for x64
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'
        architecture: x64
        cache: 'gradle'

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: java
        analysis-kinds: code-scanning,code-quality
        tools: latest
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build --no-daemon
      
    - name: Cleanup Gradle Daemons
      run: ./gradlew --stop

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        config-file: ./.github/codeql/codeql-config.yml

    - name: Cleanup Gradle Cache
      # Cleans up the Gradle caches before being cached
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties
        
        